# Generated by Django 3.2.25 on 2024-08-29 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feewaiver', '0048_contactdetails_cc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feewaiver.park'),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feewaiver.participants'),
        ),
        migrations.AlterField(
            model_name='contactdetailsdocument',
            name='contact_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='feewaiver.contactdetails'),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='contact_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_waiver', to='feewaiver.contactdetails'),
        ),
        migrations.AlterField(
            model_name='feewaiverdocument',
            name='feewaiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='feewaiver.feewaiver'),
        ),
        migrations.AlterField(
            model_name='feewaiverlogdocument',
            name='log_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='feewaiver.feewaiverlogentry'),
        ),
        migrations.AlterField(
            model_name='feewaiverlogentry',
            name='fee_waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comms_logs', to='feewaiver.feewaiver'),
        ),
        migrations.AlterField(
            model_name='feewaiveruseraction',
            name='fee_waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='feewaiver.feewaiver'),
        ),
        migrations.AlterField(
            model_name='feewaiveruseraction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
